### ISSUE TITLE
20231016 복호화 관련

### ISSUE THREAD

**Issue by MisooKim2** [00dasang/py202309#2]
나성준 학생 안녕하세요.
어제 수업 시간에 복호화 안되던 이슈 관련하여, 
코드에는 문제 없으며 대신 실행 순서에 문제가 있는 것으로 보여집니다.

복호화를 하기 위해서는 한 번 암호화가 된 파일을 복호화하여야 합니다.

사용자가 암호화를 입력하면 문자의 유니코드 (정수)에 +100을 하고,
복호화를 할 경우 문자의 유니코드 (정수)에 -100을 하게 됩니다. (아래 코드 참고)
```
if choice == 1:
    token_jump = 100
elif choice == 2:
    token_jump = -100
```

암호화가 되지 않은 문자의 유니코드의 경우 0부터 값이 시작하기 때문에,
여기에 -100을 하게 되면 음수에 해당하는 문자를 찾을 수 없기 때문에 에러가 발생합니다.

파이썬 프로그램에서 복호화를 수행하기 위한 파일을 입력 받을때,
암호화된 파일을 받아서 유니코드의 범위가 100이상부터 시작하는 것을 보장해야 합니다.

궁금증이 해결되셨길 바랍니다.

**Comment by 00dasang** [comment]
감사합니다~!!!!
