### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [00dasang/py202309#3]
### 없는 파일
- challenge/week6/function.ipynb 
- practice/week5/turtle.ipynb 
- project/week8/search_engine.ipynb
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 없는 PDF 파일
- project/week8/search_engine.pdf
	- 위 파일 이름이나 위치를 다시 확인하세요. 보고서 채점이 수행되지 않습니다.

### 에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week7/todo
    - invalid syntax (<unknown>, line 15)
        - def load_tasks_from_file("task.txt"): 
        - 위에 코드에서 함수의 매개변수는 문자열을 바로 보낼 수 없습니다. 변수 이름으로 지정하고, 함수 호출 시 문자열을 보내주세요
        - 또한 fp = 와 같이 완성되지 않은 코드가 있습니다. 코드를 완성해주세요.

### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week3/list_and_tuple
    - 29:Using variable 'item' before assignment	singer.append(item)
         - item 변수가 선언되지 않았습니다. item 변수를 선언 후 값을 할당해주세요.
- WARNING in challenge/week4/condition
    - 24:Undefined variable 'wnid'	elif rain != 'n' or rain != 'y' or wind != 'n' or wnid != 'y':
         -  wnid 오타가 있습니다. 수정해주세요
- WARNING in challenge/week7/todo_extend
    - 10:Undefined variable 'i'	            task = task_list[i]
    - 11:Undefined variable 'i'	            print(f"{i+1}. {task}")
    - 9:Unused variable 'I'	        for I in range(len(task_list)):
        - for 문에 변수는 I (대문자 i)로 선언하고, 리스트에 접근하기 위해서는 소문자 i 를 사용하고 있습니다. 모두 소문자로 맞춰주세요. 

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in challenge/week4/condition
    - 추출된 주석: # P r o g r a m .   H a v e   a   n i c e   d a y !
- Insufficient comments in challenge/week7/todo
- Insufficient comments in challenge/week7/todo_extend
    - 추출된 주석: # g e t _ t h e _ f i l e _ n a m e _ f r o m _ u s e r s

**Comment by 00dasang** [comment]
전부다 해결했습니다~!!!!
